### ISSUE TITLE
[BUG]: object spawner /saves

### ISSUE THREAD

**Issue by Beginner555989** [YimMenu-Lua/Samurais-Scripts#10]
### Describe The Bug

thank you for the saves its great job ,, but we have problem if we spawn more than 1 object it buged out

### Steps To Reproduce

![Screenshot (116)](https://github.com/user-attachments/assets/43ab3f0a-9c0e-4bcf-ba8a-8ba660968e27)
![Screenshot (117)](https://github.com/user-attachments/assets/690a5876-be4e-4b30-8189-46686eef674b)

**Comment by xesdoog** [comment]
> if we spawn more than 1 object it buged out

From which tab are you spawning multiple objects?

**Comment by Beginner555989** [comment]
> > if we spawn more than 1 object it buged out
> 
> From which tab are you spawning multiple objects?

i just press the (spawn) how can i multipler object?

**Comment by xesdoog** [comment]
> i just press the (spawn) how can i multipler object?

The feature has 2 tabs that are self explanatory:

**1. Spawn & Create:**
   - Here you can spawn as many objects as you want. If you attach one or more objects to yourself, you can save them as an outfit (you can attach as many objects as you want but don't go crazy).
   - If you want to turn yourself into a robot, spawn a camera and attach it to your head then spawn 2 katanas or whatever you want for arms and attach each one to each of your arms, if you want a big peen you can spawn a rocket and attach it to your root too. Once you're satisfied with every prop placement, press the save button, give your creation a name then save it. That's it.
  
**2. Saved Props:**
   - Here you can spawn your **SAVED OUTFITS** with as many props as they have. The issue you mentioned is not a bug, you can only spawn one creation / saved outfit at a time.
