### ISSUE TITLE
[BUG]: allocate memory reliable crash

### ISSUE THREAD

**Issue by Kibasmoothie** [YimMenu-Lua/Samurais-Scripts#12]
### Describe The Bug

Whenever i use this script after some minutes i get "[WARN/allocate_memory_reliable.cpp:35] Failed to allocate 172 bytes for reliable message, free space: 55632. Trying to free some memory" in my console. And it even goes that far that its rapidly triggering. It always ends with my session being emptied and me staying solo. No idea when this occurs im only using pops and bangs from teh script rn. Nothing else. idk 

### Steps To Reproduce

I have no idea. Use the script and click through the menu

### Log

[cout.log](https://github.com/user-attachments/files/16717891/cout.log)

### Screenshot / Video

![image](https://github.com/user-attachments/assets/0c3fa28d-f048-47d8-8f1e-384362293cbb)

**Comment by xesdoog** [comment]
That has happened to other people who don't use any scripts, Several issues were opened in YimMenu about that error, I've been trying to find one of them and check if it was resolved or if the cause was determined. I'll get back to you when I find them but I don't think this is caused by the script

**Comment by Kibasmoothie** [comment]
Yeah i monitored it and it didnt occure again. it was just sometimes. Shouldnt be connected to your script.

**Comment by xesdoog** [comment]
> Yeah i monitored it and it didnt occure again. it was just sometimes. Shouldnt be connected to your script.

I couldn't fin the issues but I'll let you know or tag you if I find one of them.
