### ISSUE TITLE
[REQUEST]: NOS exhaust visual and sound toggleable

### ISSUE THREAD

**Issue by Djizox** [YimMenu-Lua/Samurais-Scripts#15]
### Problem

NOS sound is too loud and can be unbearable. 

### Solution

toggle able NOS sound. 
toggle able NOS exhaust visual

**Comment by xesdoog** [comment]
This was an option but I removed it to keep the UI compact. I will add those toggles back but I'll put them in the window where you can set the power gain.

**Comment by Djizox** [comment]
awesome, super quick. keep up the good work :D
