### ISSUE TITLE
[REQUEST]: Burnout Smoke

### ISSUE THREAD

**Issue by Kibasmoothie** [YimMenu-Lua/Samurais-Scripts#17]
### Problem

Just realized what Drift Tire smoke is (smoke grenade basically) and i wonder if its possible to give the tires that smoke effect without drift tires to basically overwrite the normal default smokes you get in LSC. Would look insane to do Burnouts etc.

### Solution

No idea how but can´t be that hard?? (I have no idea) 

### Additional context

Awesome Lua btw gotta be my favorite ngl

**Comment by xesdoog** [comment]
> No idea how but can´t be that hard?? (I have no idea)

No it's simple actually. Good suggestion, let me test it rq then I'll add it under the **Drift Mode** sub-tab. It will not require drift mode to be enabled, I'll just put it there for convenience.
Also while I'm at it, it would probably be for the better if the drift / burnout smoke color also changes the LSC tire smoke so, that will be added too.

**Comment by Kibasmoothie** [comment]
"Let me test it rq" bro took 20 mins to make that.
Im impressed ty i will try the feature

**Comment by xesdoog** [comment]
> "Let me test it rq" bro took 20 mins to make that. Im impressed ty i will try the feature

It's half assed. The smoke doesn't look natural and the custom color reverts when you change vehicles. I'll try and make it better in the next update.
