### ISSUE TITLE
[REQUEST]: I can't find any option in my Yim Menu.

### ISSUE THREAD

**Issue by mahmudalamsagor** [YimMenu-Lua/Samurais-Scripts#19]
### Problem

I have copied the **samurais_scripts.lua** file into the Yim Menu Scripts folder, but I can't find any option in the scripts. Could you tell me what I am doing wrong?

### Solution

None

**Comment by xesdoog** [comment]
The script has 6 files in total, not just one. Downlad the [zip release](https://github.com/YimMenu-Lua/Samurais-Scripts/releases/download/v1.2.5/Samurais_Scripts_v1.2.5.zip) and extract it in your scripts folder.
