### ISSUE TITLE
[REQUEST]: Vehicle Mine Rebind

### ISSUE THREAD

**Issue by Kibasmoothie** [YimMenu-Lua/Samurais-Scripts#21]
### Problem

My No Clip shortcut is on the same button.... Either help me find the line in the code where i can change it or make us rebind it lol otherwhise i will just rebind my No clip hotkey ty

### Solution

:D

**Comment by Kibasmoothie** [comment]
Found also a little bug. Mines don´t work on any vehicle IF the vehicle is very low to the ground (My vectre) the mines will fall through the ground lol

**Comment by tupoy-ya** [comment]
> YimMenu's Lua API does not have access to a keybind system so we rely on using the game's keys which are super annoying to work with and don't give access to every button on a keyboard.

You can also use the `Wndproc` event, but it's pretty much undocumented.

```lua
event.register_handler(menu_event.Wndproc, function (hwnd, msg, wparam, lparam)
	if msg == 0x204 then
		-- Right mouse button.
		-- https://learn.microsoft.com/en-us/windows/win32/inputdev/wm-rbuttondown
		-- More can be found here:
		-- https://learn.microsoft.com/en-us/windows/win32/inputdev/mouse-input#notifications
	end

	-- pseudocode beyond this point.

	if msg == 0x0100 then
		-- Keyboard key down
		-- https://learn.microsoft.com/en-us/windows/win32/inputdev/wm-keydown
		-- More can be found here:
		-- https://learn.microsoft.com/en-us/windows/win32/inputdev/keyboard-input#notifications
		if wparam == 0x45 then
			-- 'E' pressed
			-- More can be found here:
			-- https://learn.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes
		end
	end
end)
```

**Comment by xesdoog** [comment]
> You can also use the `Wndproc` event, but it's pretty much undocumented.

I had no idea this existed, thanks for letting me know about it! I really need to read the docs again or at least check out what's been added but I feel like I'm losing passion about pretty much everything.

**Comment by xesdoog** [comment]
@Kibasmoothie I've added a new hotkey system so you can change the keybinds. Thanks to @tupoy-ya for saving my ass again! 😓

If you could please try the mines and see if they still drop through the floor or not. I've tested the changes on a super low Vectre and they seemed fine. Further feedback would be appreciated.
![superlowvectre](https://github.com/user-attachments/assets/0b1b54de-474b-4df1-8d65-5d581c458ef7)

**Comment by Kibasmoothie** [comment]
Wow insane work!! I will try this when I wake up

**Comment by Kibasmoothie** [comment]
Yep all works flawlessly! Even the hotkeys support my mouse secondary buttons. Yim doesnt do that. We can close the issue
