### ISSUE TITLE
[REQUEST]: can you add space Docker to Vehicle creator

### ISSUE THREAD

**Issue by Beginner555989** [YimMenu-Lua/Samurais-Scripts#22]
### Problem

i dont finde all cars in the search 

### Solution

thanks to your work .. its great script

**Comment by xesdoog** [comment]
It's already there but the functions that grab the vehicles and displays their names is kinda retarded. the Space Docker is already there but it won't appear when you search for it. For now you can type "dune" and you'll see it but I'll fix it in the next update.
