### ISSUE TITLE
[BUG]: Hands get stuck up out of nowhere

### ISSUE THREAD

**Issue by tuiio** [YimMenu-Lua/Samurais-Scripts#23]
### Describe The Bug

Ill be doing stuff then my hands get stuck up not sure how to recreate this bug its not toggled anymore. not sure how to recreate this bug

bugged in cutscenes too

### Steps To Reproduce

idk

### Log

nah

### Screenshot / Video

https://medal.tv/clips/iFmNdxIlozpyR-lOE/vpEwqlOzc?invite=cr-MSxyaUYsNTEzNTQ5Myw

**Comment by xesdoog** [comment]
Please [read the features list](https://github.com/YimMenu-Lua/Samurais-Scripts/blob/main/FEATURES.md).

You either had the **Replace 'Point At' Action** enabled or **Ped Grabber** enabled.

Both **Ped Grabber** and **Vehicle Grabber** should not be enabled at all times, hence why they are not saved. Only enable them when you want to have fun with them and certainly not when playing heists or missions.

If you had **Replace 'Point At' Action** then just press **[B]** to put your hands up/down.
