### ISSUE TITLE
[REQUEST]: More Movement Options

### ISSUE THREAD

**Issue by Charlie5821** [YimMenu-Lua/Samurais-Scripts#26]
### Problem

As a role-playing player, I really like your role-playing style script!
At present, we only have 6 walking postures to choose from, which is somewhat monotonous.

### Solution

Hope to add more walking postures, about 10-15?
Or, like the action plugins of FiveM, all of them can be added, and players can search for the walking posture they want.

**Comment by xesdoog** [comment]
You're right. The movement options haven't been touched since YimActions was in version 0.4 or something like that. With the recent changes to the Actions tab, it makes sense to also improve that section.
I'll see what I can do about it.

**Comment by Charlie5821** [comment]
Thank you. Additionally, based on my experience playing role-playing servers, I have put forward the following ideas. It would be great if it could be achieved, but it's okay if it can't.

More ideas:
1. Sound loop playback, in the Sound Player field, we can loop play a certain sound
2. Replacing the machete with a samurai sword and the machete with a billiard club can coexist, and players can choose to check whether to replace the machete or the billiard club. Because I prefer holding a samurai sword with both hands. :D
3. Clothing on/off function: When we press and hold a button, a menu will appear displaying the clothing for each slot. Click on the "top" option to set the value of top to 260 This will enable the removal of the top. (The clothing with the number 260 is transparent on the biped of MP_Female.) Clicking on "undershirt" will set the value of undershirt to 15, the value of "Armor" to 0, the value of "shoes" to 35, and so on.

**Comment by xesdoog** [comment]
> Thank you. Additionally, based on my experience playing role-playing servers, I have put forward the following ideas. It would be great if it could be achieved, but it's okay if it can't.
> 
> More ideas:
> 
>     1. Sound loop playback, in the Sound Player field, we can loop play a certain sound
> 
>     2. Replacing the machete with a samurai sword and the machete with a billiard club can coexist, and players can choose to check whether to replace the machete or the billiard club. Because I prefer holding a samurai sword with both hands. :D
> 
>     3. Clothing on/off function: When we press and hold a button, a menu will appear displaying the clothing for each slot. Click on the "top" option to set the value of top to 260 This will enable the removal of the top. (The clothing with the number 260 is transparent on the biped of MP_Female.) Clicking on "undershirt" will set the value of undershirt to 15, the value of "Armor" to 0, the value of "shoes" to 35, and so on.

 I will maybe add the sound loop today along with the updated movement options but the clothing options will have to wait.

For now though, the movement options have been reworked and the number of options has been increased to 28 instead of 6.
I'll create a test branch and send you a link if you want to try them out or suggest other movement options.

**Comment by Charlie5821** [comment]
Your efficiency is so fast, Samurai， I have tried the beta version in the link.
Although many walking postures have been added, my two favorite postures have not been added. Their screenshots look like this. The names of the peds that use it are
![20241228203359_1](https://github.com/user-attachments/assets/b9fadeae-3494-4029-9b47-82e08bbc841e)
A_F_Y_GenCasPat_01

![20241228203723_1](https://github.com/user-attachments/assets/e233a9de-b316-4f0b-a77b-9bbedc5bd5c4)
A_F_Y_FemaleAgent

In addition, these two walking postures are named 'heels' and' sexy 'respectively in some action plugins of FiveM
I hope the above information can help you complete this script.
Thank you very, very much!

**Comment by Charlie5821** [comment]
Another wish
The Editor mode
When I press a button, it will enter the free field of view, and I can use the left and right directional keys or other means to adjust the focal length of the lens, that is, FOV.
If possible, I would like to use another button to control the vertical rotation of the lens to take photos with a tilt angle. Just like this picture
![3](https://github.com/user-attachments/assets/633f44dd-4708-4a54-85f5-163b4ae0ac95)

**Comment by xesdoog** [comment]
> Another wish The Editor mode When I press a button, it will enter the free field of view, and I can use the left and right directional keys or other means to adjust the focal length of the lens, that is, FOV. （ The FOV of YimMenu's built-in free lens mode is too large. Images may experience distortion） If possible, I would like to use another button to control the vertical rotation of the lens to take photos with a tilt angle. Just like this picture ![3](https://private-user-images.githubusercontent.com/192959869/399080951-633f44dd-4708-4a54-85f5-163b4ae0ac95.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUzOTMzNzEsIm5iZiI6MTczNTM5MzA3MSwicGF0aCI6Ii8xOTI5NTk4NjkvMzk5MDgwOTUxLTYzM2Y0NGRkLTQ3MDgtNGE1NC04NWY1LTE2M2I0YWUwYWM5NS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyOFQxMzM3NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNzg2OTQyYTIwM2FmYzBlYWY0YTJjZjEwYTlhNDk3ZmU3YTNlZDMwNjBhMTkyNTUzNDlmNzkyNTczZTkwMDc4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.IbCPRyqQe0TSHiLJHGpFu6SF9RDHUAe7wPsmqoNodK8)

The best way to take screenshots is to use Rockstar Editor. Record a video and then go to single player > Rockstar Editor, from there you can adjust anything you want (FOV, effects, filters, focus, etc...)

There are some Online tutorials about Rockstar Editor. I stongly suggest using it instead of freecam. Here are some simple example screenshots I made a long time ago using the editor:

![Screenshot 2024-02-08 195033](https://github.com/user-attachments/assets/414cb2a1-0840-4e46-9bda-86658783e5e5)

![Screenshot 2024-02-02 155443](https://github.com/user-attachments/assets/a76a2e42-6283-454c-85a1-7344582f20cc)

![Screenshot 2024-02-08 040632](https://github.com/user-attachments/assets/78cf2eb8-83c4-44cd-ae19-b93c0fdc8025)

**Comment by xesdoog** [comment]
> Your efficiency is so fast, Samurai， I have tried the beta version in the link. Although many walking postures have been added, my two favorite postures have not been added. Their screenshots look like this. The names of the peds that use it are ![20241228203359_1](https://private-user-images.githubusercontent.com/192959869/399080114-b9fadeae-3494-4029-9b47-82e08bbc841e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUzOTMzNzEsIm5iZiI6MTczNTM5MzA3MSwicGF0aCI6Ii8xOTI5NTk4NjkvMzk5MDgwMTE0LWI5ZmFkZWFlLTM0OTQtNDAyOS05YjQ3LTgyZTA4YmJjODQxZS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyOFQxMzM3NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZmYyMDBhODRkYzFkYjM1ZjVjYzlhZGFjYjg5M2RlN2UyNTFhYzUyMGQxMzM4YWVmMTIwMTU0NDAzNWNkZmQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.K--oIfR7Memk-xlb-u30Gq4yakLL3-dCaU7rCc-ef4U) A_F_Y_GenCasPat_01
> 
> ![20241228203723_1](https://private-user-images.githubusercontent.com/192959869/399080132-e233a9de-b316-4f0b-a77b-9bbedc5bd5c4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUzOTMzNzEsIm5iZiI6MTczNTM5MzA3MSwicGF0aCI6Ii8xOTI5NTk4NjkvMzk5MDgwMTMyLWUyMzNhOWRlLWIzMTYtNGYwYi1hNzdiLTliYmVkYzViZDVjNC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyOFQxMzM3NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMmNmNTkzZDRjM2M0MWM0YmFjZjhlMTJmYzEyZmExNzMwOWJlNTNkZGQzZGY5OTlkYmI2MTUyMWQ5NDgxYWQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Kcc93VhYUI_BcbM0MJjLq4bc-XiHqc7LWgBsRfwkMgg) A_F_Y_FemaleAgent
> 
> In addition, these two walking postures are named 'heels' and' sexy 'respectively in some action plugins of FiveM I hope the above information can help you complete this script. Thank you very, very much!

I think I know which ones those are. One of them is called `"femme"` if I'm not mistaken. I'll add them to the list when it's ready for release. I've also added the ability to search and apply movements through all available movement clipsets but you'll have to place a json file inside the `scripts_config` folder because putting them in a Lua table would make the script unnecessarily large. I'll explain when it's released but for now I'm gonna be off for the weekend.
