### ISSUE TITLE
[Bug?] - Attempting to index a nil value

### ISSUE THREAD

**Issue by RKDeviancy** [YimMenu-Lua/Samurais-Scripts#4]
For the first 30 or so minutes I played after updating to YimMenu's most recent Nightly and only using Samurais-Scripts, all was working fine and there were no errors being logged, hence me telling you so under the previous issue I closed. 

Just recently though, this log has showed up on repeat when clicking on "Vehicle" under Samurais-Scripts, even after restarting GTA and YimMenu:
[18:39:09.4155446][FATAL/lua_module.cpp:81] ...v\AppData\Roaming\YimMenu\scripts/lib/samurais_utils.lua:1121: attempt to index a nil value (global 'STEAMING')
stack traceback:
        ...v\AppData\Roaming\YimMenu\scripts/lib/samurais_utils.lua:1121: in field 'manufacturer'
        ...dev\AppData\Roaming\YimMenu\scripts\samurais_scripts.lua:1625: in function <...dev\AppData\Roaming\YimMenu\scripts\samurais_scripts.lua:1623>

Along with this, all of the toggles in the vehicle menu now briefly show up, before disappearing. All previous chosen settings are still active, including drift mode and the torque settings, I just cannot change the toggles anymore. I am unsure why this is happening, because literally nothing has changed between when I told you all was working as intended, and now- i've just been driving around! I apologize if this issue is because of an oversight of mine somewhere, like the previous one was. If it is not, I hope the information I have was helpful in helping you identify the problem!

**Comment by xesdoog** [comment]
Ah shit I'm too drunk to type properly... Wtf is *STEAMING*? lmao 😂
I'll fix it in a few minutes. Sorry about that

**Comment by RKDeviancy** [comment]
Hahaha no problem, and thank you! You work fast with this stuff for being drunk though LMAO

**Comment by xesdoog** [comment]
> Hahaha no problem, and thank you! You work fast with this stuff, especially being drunk though LMAO

l;ol yeah

I edited the release, it's stiill 1.1.2 but the actual .zip is fixed

**Comment by RKDeviancy** [comment]
Okay, thank you! I'll test it out soon!

**Comment by RKDeviancy** [comment]
this shows up now:

[20:40:21.2620904][FATAL/lua_module.cpp:81] ...v\AppData\Roaming\YimMenu\scripts/lib/samurais_utils.lua:1121: attempt to call a nil value (field 'IS_THIS_MODEL_A_VEHICLE')
stack traceback:
        ...v\AppData\Roaming\YimMenu\scripts/lib/samurais_utils.lua:1121: in field 'manufacturer'
        ...dev\AppData\Roaming\YimMenu\scripts\samurais_scripts.lua:1625: in function <...dev\AppData\Roaming\YimMenu\scripts\samurais_scripts.lua:1623>

**Comment by xesdoog** [comment]
I'm gonna keep the issue open in case another fuckup of mine pops up 😭

**Comment by RKDeviancy** [comment]
LOL no worries man I'll try it out rn

**Comment by RKDeviancy** [comment]
So far so good! I'll update you if that changes! Thank you again <3

**Comment by xesdoog** [comment]
Thank you for your feedback! I appreciate it.

**Comment by RKDeviancy** [comment]
So far no issues! Thank you!

**Comment by xesdoog** [comment]
> So far no issues! Thank you!

I played around with it too and it seems that I haven't messed things up a lot yesterday lol

Thanks for the help!

**Comment by RKDeviancy** [comment]
No problem!! Thank you, too!
