### ISSUE TITLE
please make sure you post respectful content

### ISSUE THREAD

**Issue by lonelybud** [YimMenu-Lua/Samurais-Scripts#5]
https://github.com/YimMenu-Lua/Samurais-Scripts/blob/62aa6503c39a159225438c74206a51fc900b955f/data/refs.lua#L347

its not funny. Kindly remove it. It raises democratic and religious concerns.

**Comment by xesdoog** [comment]
> https://github.com/YimMenu-Lua/Samurais-Scripts/blob/62aa6503c39a159225438c74206a51fc900b955f/data/refs.lua#L347
> 
> its not funny. Kindly remove it. It raises democratic and religious concerns.

Sorry I was just joking. Will remove it immediately.

**Comment by xesdoog** [comment]
@lonelybud removed in [df8770c](https://github.com/YimMenu-Lua/Samurais-Scripts/commit/df8770c2f5496d5628d3f5c70c049158a429f002)

Sorry again!

**Comment by lonelybud** [comment]
thanks
