### ISSUE TITLE
[bug??] player makes scared npc noises when ragdolling or falling 

### ISSUE THREAD

**Issue by cyanidesoup** [YimMenu-Lua/Samurais-Scripts#6]

**Comment by xesdoog** [comment]
> 

Not a bug, it's one of the hidden features. Do you want an option to disable it?

**Comment by cyanidesoup** [comment]
yea, its a bit annoying, thanks

**Comment by xesdoog** [comment]
> yea, its a bit annoying, thanks

No problem. Your request will be added in the next update.
