### ISSUE TITLE
[REQUEST]: Move `data/` and `lib/` directories to includes.

### ISSUE THREAD

**Issue by tupoy-ya** [YimMenu-Lua/Samurais-Scripts#9]
### Problem

YimMenu now supports putting files into the `includes/` directory to avoid them being loaded.
From what I have seen nothing in `data/` or `lib/` actually runs on it's own and is meant to be required by `samurais_scripts.lua`, `includes/` was added for this exact situation.

### Solution

1. Create a directory called `includes/`
2. Move `data/` into it.
3. Move `lib/` into it.

### Additional context

The file structure may not look as good, but it is less confusing for the end user because they will not have 6 scripts and only 1 of them is the one they may want to disable, instead they will just have 1 script.

**Comment by xesdoog** [comment]
Yes that makes sense. I've seen your PR about that and forgot to adjust. Thank you!
